// <auto-generated />
using System;
using DentApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DentApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614233029_IslemKaydiGelirGiderLink")]
    partial class IslemKaydiGelirGiderLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DentApp.API.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("DentApp.API.Models.GelirGider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GelirGiderler");
                });

            modelBuilder.Entity("DentApp.API.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AtananCalisanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtanmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BaslamaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Oncelik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SonTarih")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtananCalisanId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("DentApp.API.Models.IslemKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoktorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FarkliTutar")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GelirGiderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notlar")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OdenenTutar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SistemFiyati")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("TedaviId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoktorId");

                    b.HasIndex("TedaviId");

                    b.ToTable("IslemKayitlari");
                });

            modelBuilder.Entity("DentApp.API.Models.RandevuTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GorusenCalisanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IptalSebebi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TercihTarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GorusenCalisanId");

                    b.ToTable("RandevuTalepleri");
                });

            modelBuilder.Entity("DentApp.API.Models.StokKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimumMiktar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SonGuncelleme")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StokKalemleri");
                });

            modelBuilder.Entity("DentApp.API.Models.Tedavi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TemelFiyat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tedaviler");
                });

            modelBuilder.Entity("DentApp.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CalisanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DentApp.API.Models.Vardiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalisanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Not")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.ToTable("Vardiyalar");
                });

            modelBuilder.Entity("DentApp.API.Models.Gorev", b =>
                {
                    b.HasOne("DentApp.API.Models.Calisan", "AtananCalisan")
                        .WithMany()
                        .HasForeignKey("AtananCalisanId");

                    b.Navigation("AtananCalisan");
                });

            modelBuilder.Entity("DentApp.API.Models.IslemKaydi", b =>
                {
                    b.HasOne("DentApp.API.Models.Calisan", "Doktor")
                        .WithMany()
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentApp.API.Models.Tedavi", "Tedavi")
                        .WithMany()
                        .HasForeignKey("TedaviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Tedavi");
                });

            modelBuilder.Entity("DentApp.API.Models.RandevuTalebi", b =>
                {
                    b.HasOne("DentApp.API.Models.Calisan", "GorusenCalisan")
                        .WithMany()
                        .HasForeignKey("GorusenCalisanId");

                    b.Navigation("GorusenCalisan");
                });

            modelBuilder.Entity("DentApp.API.Models.User", b =>
                {
                    b.HasOne("DentApp.API.Models.Calisan", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanId");

                    b.Navigation("Calisan");
                });

            modelBuilder.Entity("DentApp.API.Models.Vardiya", b =>
                {
                    b.HasOne("DentApp.API.Models.Calisan", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");
                });
#pragma warning restore 612, 618
        }
    }
}
